import { StyleSheet } from "react-native";

export const homeStyles = (theme) => StyleSheet.create({
  avatarContainer: {
    position: "relative",
    width: 90,
    height: 90,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarWrapper: {
    borderWidth: 3,
    borderColor: theme.colors.primary,
    borderRadius: 45,
    overflow: "hidden",
  },
  editButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.primary,
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  statsContainer: {
    padding: 20,
    gap: 15,
  },
  statCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    padding: 20,
    borderWidth: 2,
    borderColor: theme.colors.outlineVariant,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statIconContainer: {
    backgroundColor: theme.colors.primaryContainer,
    borderRadius: 30,
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
  },
  statContent: {
    flex: 1,
    marginLeft: 15,
  },
  statLabel: {
    fontSize: 14,
    color: theme.colors.onSurfaceVariant,
    fontFamily: "monospace",
    letterSpacing: 1,
    marginBottom: 5,
  },
  statValue: {
    fontSize: 32,
    fontWeight: "bold",
    color: theme.colors.primary,
    fontFamily: "monospace",
  },
});
